---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotemplate
  labels:
    app.kubernetes.io/name: gotemplate
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gotemplate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gotemplate
    spec:
      containers:
        - name: gotemplate
          image: gotemplate
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
            - name: GOWON_GOTEMPLATE_CONFIG
              value: /config/config.yaml
          volumeMounts:
            - name: gotemplate-config
              mountPath: /config/config.yaml
              subPath: config.yaml
      volumes:
        - name: gotemplate-config
          configMap:
            name: gotemplate-config
